name: PHP syntax checker

on: [push]

jobs:
  lint:
    name: Linter
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Check syntax
        run: php -l src tests
